### ISSUE TITLE
Traceback (most recent call last):   File "train.py", line 185, in <module>     psnr_val_rgb = torch.stack(psnr_val_rgb).mean().item() RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by luanqi123** [INVOKERer/DeepRFT#42]
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    psnr_val_rgb = torch.stack(psnr_val_rgb).mean().item()
RuntimeError: stack expects a non-empty TensorList
![捕获](https://user-images.githubusercontent.com/76938355/190586450-d4450ea9-5ee9-4591-8cd6-fe5a603e0f4f.PNG)

训练模型训练到一半时报这个错误，不知道作者有没有遇到过？

**Comment by luanqi123** [comment]
是不是我数据集整理的格式不太正确

**Comment by luanqi123** [comment]
psnr_val_rgb这个变量好像是空

**Comment by INVOKERer** [comment]
这种情况可能是val的路径有误

**Comment by luanqi123** [comment]
解决了 谢谢作者  还有一个问题 你这个模型训练最后的loss降到多少呀，我这里降低到50以后，就不往下掉了

**Comment by INVOKERer** [comment]
实验时主要会看验证集的PSNR，loss的大小已经记不得了。

**Comment by INVOKERer** [comment]
实验时主要会看验证集的PSNR，loss的大小已经记不得了。
