### ISSUE TITLE
RuntimeError: cuFFT error: CUFFT_INVALID_SIZE

### ISSUE THREAD

**Issue by HelloWorldYYYYY** [INVOKERer/DeepRFT#44]
@INVOKERer  您好 作者 ，您的作品非常具有创造性，以至于我不得不加入我的网络尝试一下效果，我在训练的过程中遇到了相关的问题，您有遇到过如下的代码吗？

```
  0%|          | 0/10 [44:48<?, ?it/s]
Traceback (most recent call last):
  File "E:\UIDGain++\train.py", line 101, in <module>
    main()
  File "E:\UIDGain++\train.py", line 59, in main
    model.update_D(images_a, images_b)
  File "E:\UIDGain++\model.py", line 180, in update_D
    self.forward()
  File "E:\UIDGain++\model.py", line 128, in forward
    self.z_content_i, self.z_content_b = self.enc_c.forward(self.real_I_encoded, self.real_B_encoded)
  File "E:\UIDGain++\networks.py", line 135, in forward
    outputA = self.convA(xa)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\UIDGain++\networks.py", line 798, in forward
    y = torch.fft.rfft2(x, norm=self.norm)
RuntimeError: cuFFT error: CUFFT_INVALID_SIZE

Process finished with exit code 1
```

**Comment by HelloWorldYYYYY** [comment]
期待您的回信

**Comment by INVOKERer** [comment]
如果代码上没问题，我之前因为显卡驱动等因素也遇到过类似的问题，重装pytorch可能可以解决此问题。

**Comment by HelloWorldYYYYY** [comment]
@INVOKERer 我是网络跑了20个epoch 突然出现的问题，跑了8h，我猜测也是驱动硬件等问题，代码估计没问题

**Comment by 936041352** [comment]
I have also encountered this problem. Have you resolved it?
