### ISSUE TITLE
关于测试图像的大小

### ISSUE THREAD

**Issue by nihao-eng** [INVOKERer/DeepRFT#49]
请问作者预训练的模型对测试图像的大小有要求吗？为何我运行 test.py 时出现以下错误

Traceback (most recent call last):
  File "test.py", line 64, in <module>
    input_re, batch_list = window_partitionx(input_, win)
  File "/home/zzu/xkuo/DeepRFT-main/layers.py", line 247, in window_partitionx
    x_r = window_partitions(x[:, :, :h, -window_size:], window_size)
  File "/home/zzu/xkuo/DeepRFT-main/layers.py", line 213, in window_partitions
    x = x.view(B, C, H // window_size, window_size, W // window_size, window_size)
RuntimeError: shape '[1, 3, 1, 256, 0, 256]' is invalid for input of size 58368

**Comment by INVOKERer** [comment]
可能是我之前的代码有bug，你可以先尝试https://github.com/DeepMed-Lab-ECNU/DeepRFT-AAAI2023/blob/main/basicsr/models/archs/FMIMOUNet_arch.py中的方法进行测试。

**Comment by INVOKERer** [comment]
我更新了一版layers.py文件，不知道能不能解决这个问题。

**Comment by nihao-eng** [comment]
> 

首先非常感谢作者的杰出贡献，问题出在我的测试图像太小了，我将参数 --win_size 设置为32可以运行，但似乎对我的测试图像没有效果。

**Comment by INVOKERer** [comment]
可以试试不设置win_size，因为对于我们的方法，模型的训练和测试尺度要尽可能相似。
